### ISSUE TITLE
KM change of epoch process requires many calls to the contract

### ISSUE THREAD

**Issue by AvishaiW** [scrtlabs/enigma-contract#135]
Hey,
When the KM goes through the process of creating a new epoch, it requires 4 calls to the enigma contract: 
1. get_active_workers.
2. set_worker_params
3. count_secret_contracts
4. get_secret_contract_addresses
which leads to a long delay in the process on the KM side of changing into a new epoch.
Since this process happens all of the time and since all of the calls are necessary for the process I would like that we would consider concatenating some of the methods (at least 3 & 4) in order to reduce the number of calls to the contract in order to speed the things up in that area.

**Comment by AvishaiW** [comment]
@apalepu23 yeah, I think that won't give us a major improvement, however, I would like the change to be done. Maybe you can add to the existing `getSecretContractAddressesImpl` that if it receives `0` or something in that sort, it will send back all SC addresses (but whatever you think will be clearer and easier to implement) Thanks!

**Comment by AvishaiW** [comment]
@apalepu23 what is the status on this?

**Comment by lacabra** [comment]
@avishaiW: implemented in #139
