### ISSUE TITLE
Output hash of a secret contract

### ISSUE THREAD

**Issue by lenak25** [scrtlabs/enigma-contract#28]
Hi @apalepu23 ,

Several questions about the `outputHash` field of the `SecretContract` struct:
1. What is the purpose of this field?
2. Why is it a single value and not an array, like the deltas?

Thanks!

**Comment by apalepu23** [comment]
Closing this issue since it was resolved by associating `outputHash` with individual task records (`5a466c377ca8e9c74fefbd7f4705e2d25b5992c4`; PR #87 )
