### ISSUE TITLE
Enable an easy way to retrieve task result information  

### ISSUE THREAD

**Issue by lenak25** [scrtlabs/enigma-contract#35]
Hi @apalepu23 ,

When a worker receives a `TaskResult` it has to verify the following:
- For `Compute` task: verify the `output` and the new `delta`
- For `Deploy` task: verify the `code`(==`output`) and the first `delta`
In the current implementation, there is no easy way to do this.
Please add a new function or add the missing info to the `TaskRecord` object.

Thanks

**Comment by lacabra** [comment]
Closed via #87
