### ISSUE TITLE
Add the delta key/s to the ReceiptVerified and ReceiptsVerified events

### ISSUE THREAD

**Issue by lenak25** [scrtlabs/enigma-contract#56]
Hi,

The index of the deltas is missing from the `ReceiptVerified`and `ReceiptsVerified` events. Please add the required information.

Thanks,
Lena

**Comment by lacabra** [comment]
Fixed through #138. This is now properly tested with `ReceiptVerified`.

`ReceiptsVerified` (plural/array) also implements this with a different name, but since it's not used, I'm leaving it as is. When the need comes, we can adjust the names across repos.
