### ISSUE TITLE
Execution of erc20 contract runs out of gas

### ISSUE THREAD

**Issue by lacabra** [scrtlabs/enigma-contract#75]
After @AvishaiW fixing [115](https://github.com/enigmampc/enigma-core/issues/115) in `core`, I adjusted the integrationTest to execute a secret computation on the erc20 contract [here](https://github.com/enigmampc/enigma-contract/blob/develop/enigma-js/test/integrationTests/template.10_execute_erc20.js), but the test fails because `core` reports running out of gas:
```
Error in execution of smart contract function: Invocation resulted in gas limit violated
```
As reported in [117](https://github.com/enigmampc/enigma-core/issues/117) in `core`, it is not an out-of-gas per se (and the gas limit is set to 10M, which is more than enough to run that computation), but a mismatch in the parameters that are passed to the computation. Thus, I would appreciate if @AvishaiW could troubleshoot this issue.

The order of integration tests to run to troubleshoot this issue are as follows:
```
01_init.spec.js
02_deploy_erc20.spec.js
10_execute_erc20.spec.js
```

**Comment by AvishaiW** [comment]
hey @lacabra, it's not clear how to reproduce this issue, can you please elaborate as to how and where I should run this js files? I didn't find them in any of our repositories. Thanks!

**Comment by lacabra** [comment]
Read this [README](https://github.com/enigmampc/discovery-integration-tests#running-individual-tests), especially the section "Running Individual Tests". The test files are [here](https://github.com/enigmampc/enigma-contract/tree/develop/enigma-js/test/integrationTests), and as the README says, the test files will be generated from the corresponding templates.

**Comment by AvishaiW** [comment]
After looking in the core tests, it seems that 10M isn't enough for the erc20 executions. try running them with a higher limit, more like 40M
